---
- name: Deploying to slave
  hosts: " {{ passed_in_hosts }}"
  remote_user: ec2-user
  become_user: root

  # tasks:
  # - name: Add the user 'test' with a specific uid to test the playbook
  #   user:
  #     name: test
  #     comment: test user to be removed
  #     expires: 1624869025  
  roles:
    - geerlingguy.docker