---
- name: Deploying to master
  hosts: " {{ passed_in_hosts }}"
  remote_user: ec2-user
  become_user: root
  vars:
    awscli_install_os_dependencies: true
    awscli_install_dir: /opt/awscli/bin
    awscli_bin_dir: /usr/bin
    awscli_venv_name: current
    jenkins_prefer_lts: false

  # tasks:
  # - name: Add the user 'test' with a specific uid to test the playbook
  #   user:
  #     name: test
  #     comment: test user to be removed
  #     expires: 1624869025

  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.ansible
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.docker
    - xanmanning.awscli

  tasks:
    - name: Install basic packages
      yum:
        name: " {{ item }}"
        state: present
      with_items:
        - telnet
        - wget
        - vim

    - name: Sync the jenkins files with s3.
