---
- name: Deploying to master
  hosts: " {{ passed_in_hosts }}"
  remote_user: ec2-user
  become_user: root
  become: true


  tasks:
    # - name: Install basic packages
    #   yum:
    #     name: " {{ item }}"
    #     state: present
    #   with_items:
    #     - telnet
    #     - wget
    #     - vim
    #     - git

    # - name: Delete all the files within /var/lib/jenkins
    #   file:
    #     path: /var/lib/jenkins
    #     state: absent

      
    - name: List all the objects and save it.
      aws_s3:
        bucket: kiran-jenkins-dev-2390185-s3-bucket
        # prefix: /
        mode: list
      register: s3objects


    - name: Download all the objects.
      aws_s3:
          bucket: "bucketname"
          object: "{{ item }}"
          mode: get
          dest: "/var/lib/jenkins"
      with_items: "{{ s3objects.s3_keys }}"
      notify: Restart jenkins

  handlers:
    - name: Restart jenkins
      service:
        name: jenkins
        state: restarted