#!/bin/bash

#Creating directories
mkdir /home/ec2-user/python_venv

#Installing git
sudo yum install git -y

#Cloning git repo
git clone https://github.com/kiranaaditya/terraform_samples.git

#Installing terraform
wget https://releases.hashicorp.com/terraform/1.0.3/terraform_1.0.3_linux_amd64.zip
sudo unzip terraform_1.0.3_linux_amd64.zip
sudo mv terraform /usr/bin/

#Installing python
sudo yum install gcc openssl-devel bzip2-devel libffi-devel -y
cd /opt
sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
sudo tar xzf Python-3.9.6.tgz
cd Python-3.9.6 
sudo ./configure --enable-optimizations
sudo make altinstall
rm -rf /opt/Python-3.9.6.tgz

#Creating python env
python3.9 -m venv /home/ec2-user/python_venv
source /home/ec2-user/python_venv/bin/activate
cd ~

#Installing ansible for the env
python3.9 -m pip install --upgrade pip
python3.9 -m pip install ansible
