---
  - name: Remove default docker packages
    yum:
      name: "{{ docker_packages_to_remove }}"
      state: absent

  - name: Install yum-utils
    yum:
      name: yum-utils
      state: present

  - name: Download and install the docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker.repo
      mode: 0400

  - name: Install docker packages
    yum:
      name: "{{ docker_packages_to_install }}"
      state: present

# Creating a docker.service.d drop-in directory
  - name: Create a docker.service.d directory if it does not exist
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      mode: '0755'

# Copying override.conf within the docker.service.d directory
  - name: Copy file with owner and permissions
    become: yes
    copy:
      src: files/override.conf
      dest: /etc/systemd/system/docker.service.d/override.conf
      owner: root
      group: root
      mode: '0644'
    notify:
      - Daemon reload
      - Start services